#!/bin/sh
#
# __ __| |           |  /_) |     ___|             |           |
#    |   __ \   _ \  ' /  | |  / |      _ \ __ \   |      _` | __ \   __|
#    |   | | |  __/  . \  |   <  |   |  __/ |   |  |     (   | |   |\__ \
#   _|  _| |_|\___| _|\_\_|_|\_\\____|\___|_|  _| _____|\__,_|_.__/ ____/
#
# BOOTSTRAP script for MPC device.
# POST AZ01-LAUNCH-MPC script

SCRIPT_NAME=$(readlink -f "$0")
SCRIPT_DIR=$(dirname "$SCRIPT_NAME")
source "$SCRIPT_DIR/tkgl_path"

# -----------------------------------------------------------------------------
# Read the doer_list at the tkgl_root dir

[ -f "$TKGL_ROOT/doer_list" ] || exit 1

cat "$TKGL_ROOT/doer_list">>$TKGL_LOG
source "$TKGL_ROOT/doer_list"

# -----------------------------------------------------------------------------

# for debugging purpose locally:
if [ "x$TKGL_PATH_FILE" == "x" ]
then
  export TKGL_PATH_FILE=$(dirname $(readlink -f "$0"))/tkgl_path
fi

source $TKGL_PATH_FILE


echo "-------------------------------------------------------------------------">$TKGL_LOG
echo " TKGL_BOOTSTARP SCRIPT : $TKGL_BOOTSTRAP" >> $TKGL_LOG
date >> $TKGL_LOG
uname -a >> $TKGL_LOG
echo >> $TKGL_LOG
for MODULE in $TKGL_DOER ; do
   echo  >> $TKGL_LOG
   echo "-------------------------------------------------------------------------" >>$TKGL_LOG
   echo "-- Module $MODULE --">>$TKGL_LOG
   echo "-------------------------------------------------------------------------" >>$TKGL_LOG
   _MODULE_LAUNCH_SCRIPT="$TKGL_ROOT/modules/mod_$MODULE/tkgl_mod_$MODULE.sh"
  if [ -f "$_MODULE_LAUNCH_SCRIPT" ]
   then
      echo "Launch script $_MODULE_LAUNCH_SCRIPT found."
      sh "$TKGL_ROOT/modules/mod_$MODULE/tkgl_mod_$MODULE.sh"
   else
      echo "*** Error : launch script $_MODULE_LAUNCH_SCRIPT not found"
   fi
done
