#!/bin/sh
#
# __ __| |           |  /_) |     ___|             |           |
#    |   __ \   _ \  ' /  | |  / |      _ \ __ \   |      _` | __ \   __|
#    |   | | |  __/  . \  |   <  |   |  __/ |   |  |     (   | |   |\__ \
#   _|  _| |_|\___| _|\_\_|_|\_\\____|\___|_|  _| _____|\__,_|_.__/ ____/
#
# BOOTSTRAP script for MPC device.
# POST AZ01-LAUNCH-MPC script

SCRIPT_NAME=$(readlink -f "$0")
SCRIPT_DIR=$(dirname "$SCRIPT_NAME")
source "$SCRIPT_DIR/tkgl_path"

# -----------------------------------------------------------------------------
# Read the doer_list at the tkgl_root dir

[ -f "$TKGL_ROOT/doer_list" ] || exit 1 

source "$TKGL_ROOT/doer_list"

# -----------------------------------------------------------------------------

# for debugging purpose locally:
if [ "x$TKGL_PATH_FILE" == "x" ]
then
  export TKGL_PATH_FILE=$(dirname $(readlink -f "$0"))/tkgl_path
fi

source $TKGL_PATH_FILE

echo "-------------------------------------------------------------------------" > $TKGL_LOG
echo "-- In bootstrap script $TKGL_BOOTSTRAP --" >> $TKGL_LOG
echo "-------------------------------------------------------------------------" >> $TKGL_LOG
echo >> $TKGL_LOG
date >> $TKGL_LOG
uname -a >> $TKGL_LOG
echo >> $TKGL_LOG
echo  "TKGL_DOER = $TKGL_DOER " >> $TKGL_LOG
echo  >> $TKGL_LOG

for MODULE in $TKGL_DOER ; do
   echo "---- DOER Module $MODULE ----" >> $TKGL_LOG
   MODULE_SCRIPT="$TKGL_ROOT/modules/mod_$MODULE/tkgl_mod_$MODULE.sh"
   if [ -f "$MODULE_SCRIPT" ]
   then
      sh "$MODULE_SCRIPT"
   else
      echo "$MODULE_SCRIPT module script not found"  >> $TKGL_LOG
   fi
done

echo "-------------------------------------------------------------------------" >> $TKGL_LOG
